Check after creating

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -50,19 +50,19 @@ jobs:
           COVER_VERBOSE=1 cover -test
         working-directory: ${{ github.workspace }}
 
-      - name: Check for HTML report
-        run: |
-          if [ ! -f cover_html/index.html ]; then
-            echo "HTML report not found. Skipping deployment."
-            exit 1
-          fi
-
       # Generate HTML coverage report
       - name: Generate HTML report
         run: |
           mkdir -p cover_html
           cover -report html -outputdir cover_html
       # working-directory: ${{ github.workspace }}
+
+      - name: Check for HTML report
+        run: |
+          if [ ! -f cover_html/index.html ]; then
+            echo "HTML report not found. Skipping deployment."
+            exit 1
+          fi
 
       - name: Debug coverage output
         run: |
@@ -79,6 +79,6 @@ jobs:
           destination_dir: coverage
           user_name: github-actions
           user_email: github-actions@github.com
-          # Create completely new gh-pages branch
+          # Create a completely new gh-pages branch
           force_orphan: true
           keep_files: false
